### ISSUE TITLE
bower distribution

### ISSUE THREAD

**Issue by srvance** [trentrichardson/Intimidatetime#5]
Hi, Trent --

I was just suggesting we try intimidatetime in a project where I'm at now. They like it but were disappointed it's not in the bower registry. They're pulling it via the git reference in the meantime.

What do you think of registering it as a bower package?

http://bower.io/docs/creating-packages/

Steve

**Comment by trentrichardson** [comment]
Hey Steve,

Sure I dont mind registering it. Beware it may be a little raw around the
edges and I've not had much time recently to polish it.  (It is usable of
course though, just my disclaimer) :-)  I will try and take a look into
registering it between tonight and end of the weekend.

Hope you're doing well!

Trent

**Comment by trentrichardson** [comment]
Ok, it is now registered in bower as Intimidatetime
